export const GET_ALL_PRODUCTS ="GET_ALL_PRODUCTS";
export const GET_PRODUCT_BY_ID_IF ="GET_PRODUCT_BY_ID_IF";
export const GET_PRODUCT_DETAIL_BY_CLICK="GET_PRODUCT_DETAIL_BY_CLICK";
export const LOGIN ="LOGIN";
export const SIGNUP="SIGNUP";
export const VERIFY_EMAIL="VERIFY_EMAIL";
export const KEEP_LOGIN_STATE="KEEP_LOGIN_STATE";